export const WRAPPER_CONFIG_PATH = '.xomda/wrapper/xomda-wrapper.json'

export const POSIX_SCRIPT = `#!/usr/bin/env sh
# xomdaw — bootstraps the pinned xomda version into .xomda/wrapper/ and execs it.
# Generated by \`xomda wrapper\`. Safe to check into source control.
set -e

# Resolve the directory containing this script, following symlinks.
PRG="$0"
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \\(.*\\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")/"$link"
  fi
done
ROOT=$(cd "$(dirname "$PRG")" && pwd)

CONFIG="$ROOT/.xomda/wrapper/xomda-wrapper.json"
CACHE="$ROOT/.xomda/wrapper"

if [ ! -f "$CONFIG" ]; then
  echo "xomdaw: missing $CONFIG" >&2
  echo "  Run \\\`npx xomda wrapper\\\` to (re)generate the wrapper config." >&2
  exit 1
fi

VERSION=$(node -e "process.stdout.write(require(process.argv[1]).version || '')" "$CONFIG")
if [ -z "$VERSION" ]; then
  echo "xomdaw: $CONFIG has no \\"version\\" field" >&2
  exit 1
fi

INSTALLED_PKG="$CACHE/node_modules/xomda/package.json"
INSTALLED_VERSION=""
if [ -f "$INSTALLED_PKG" ]; then
  INSTALLED_VERSION=$(node -e "process.stdout.write(require(process.argv[1]).version || '')" "$INSTALLED_PKG")
fi

# (Re)install if missing or version mismatch. Always reinstall for path/url specs.
NEEDS_INSTALL=0
case "$VERSION" in
  file:*|http:*|https:*|/*|./*|../*|*.tgz) NEEDS_INSTALL=1 ;;
  *)
    if [ "$INSTALLED_VERSION" != "$VERSION" ]; then NEEDS_INSTALL=1; fi
    ;;
esac

if [ "$NEEDS_INSTALL" = "1" ]; then
  echo "xomdaw: downloading xomda@$VERSION ..." >&2
  mkdir -p "$CACHE"
  node -e "require('fs').writeFileSync(process.argv[1]+'/package.json', JSON.stringify({ private: true, dependencies: { xomda: process.argv[2] } }, null, 2))" "$CACHE" "$VERSION"
  (cd "$CACHE" && npm install --no-audit --no-fund --silent)
fi

BIN_REL=$(node -e "var b=require(process.argv[1]).bin; process.stdout.write(typeof b==='string'?b:(b&&b.xomda)||'')" "$INSTALLED_PKG")
if [ -z "$BIN_REL" ]; then
  echo "xomdaw: installed xomda package has no bin.xomda entry" >&2
  exit 1
fi

exec node "$CACHE/node_modules/xomda/$BIN_REL" "$@"
`

export const WINDOWS_SCRIPT = `@ECHO OFF
REM xomdaw.cmd - bootstraps the pinned xomda version into .xomda\\wrapper\\ and execs it.
REM Generated by \`xomda wrapper\`. Safe to check into source control.
SETLOCAL ENABLEDELAYEDEXPANSION

SET "ROOT=%~dp0"
IF "%ROOT:~-1%"=="\\" SET "ROOT=%ROOT:~0,-1%"

SET "CONFIG=%ROOT%\\.xomda\\wrapper\\xomda-wrapper.json"
SET "CACHE=%ROOT%\\.xomda\\wrapper"
SET "INSTALLED_PKG=%CACHE%\\node_modules\\xomda\\package.json"

IF NOT EXIST "%CONFIG%" (
  ECHO xomdaw: missing %CONFIG% 1>&2
  ECHO   Run "npx xomda wrapper" to ^(re^)generate the wrapper config. 1>&2
  EXIT /B 1
)

FOR /F "usebackq delims=" %%V IN (\`node -e "process.stdout.write(require(process.argv[1]).version || '')" "%CONFIG%"\`) DO SET "VERSION=%%V"
IF "%VERSION%"=="" (
  ECHO xomdaw: %CONFIG% has no "version" field 1>&2
  EXIT /B 1
)

SET "INSTALLED_VERSION="
IF EXIST "%INSTALLED_PKG%" (
  FOR /F "usebackq delims=" %%V IN (\`node -e "process.stdout.write(require(process.argv[1]).version || '')" "%INSTALLED_PKG%"\`) DO SET "INSTALLED_VERSION=%%V"
)

SET "NEEDS_INSTALL=0"
IF NOT "%INSTALLED_VERSION%"=="%VERSION%" SET "NEEDS_INSTALL=1"

IF "%NEEDS_INSTALL%"=="1" (
  ECHO xomdaw: downloading xomda@%VERSION% ... 1>&2
  IF NOT EXIST "%CACHE%" MKDIR "%CACHE%"
  > "%CACHE%\\package.json" ECHO {"private":true,"dependencies":{"xomda":"%VERSION%"}}
  PUSHD "%CACHE%"
  CALL npm install --no-audit --no-fund --silent
  IF ERRORLEVEL 1 (
    POPD
    EXIT /B 1
  )
  POPD
)

FOR /F "usebackq delims=" %%B IN (\`node -e "var b=require(process.argv[1]).bin; process.stdout.write(typeof b==='string'?b:(b^&^&b.xomda)||'')" "%INSTALLED_PKG%"\`) DO SET "BIN_REL=%%B"
IF "%BIN_REL%"=="" (
  ECHO xomdaw: installed xomda package has no bin.xomda entry 1>&2
  EXIT /B 1
)

node "%CACHE%\\node_modules\\xomda\\%BIN_REL%" %*
ENDLOCAL & EXIT /B %ERRORLEVEL%
`
