import type { ParticleBackgroundProps } from './ParticleBackground'

export type ParticleBackgroundPreset = Partial<ParticleBackgroundProps>

export const presets = {
  galaxy: {
    fieldFunction: 'galaxy',
    fieldParams: { arms: 4, tightness: 0.6, radius: 2.8 },
    particleCount: 8000,
    camera: { position: [0, 1.8, 6], orbitSpeed: 0.05, fov: Math.PI / 3.2 },
    baseColor: '#a8c8ff',
    dropMass: 2,
    dropVelocity: 1.5,
    damping: 0.95,
    brightness: 1,
    glow: 1,
    coreIntensity: 1.2,
    brightnessFlicker: 0.6,
    flickerSpeed: 1.2,
  },
  nebula: {
    fieldFunction: 'noise',
    fieldParams: { size: 4 },
    particleCount: 6000,
    brightnessFlicker: 0.4,
    flickerSpeed: 0.6,
    particleSize: 320,
    baseColor: '#ff7ad9',
    pointerStrength: 2,
    camera: { position: [0, 0, 4.5] },
    brightness: 0.9,
    glow: 2.4,
    coreIntensity: 0.4,
  },
  lattice: {
    fieldFunction: 'lattice',
    fieldParams: { size: 3 },
    particleCount: 4096,
    particleSize: 140,
    springStrength: 1.5,
    camera: { position: [4, 3, 5], fov: Math.PI / 4, orbitSpeed: 0.04 },
    brightnessFlicker: 0.2,
    flickerSpeed: 1,
    brightness: 1.1,
    glow: 0.6,
    coreIntensity: 1.5,
  },
  pulse: {
    fieldFunction: 'sphere',
    fieldParams: { radius: 1.6 },
    particleCount: 5000,
    dropMass: 4,
    dropVelocity: 3,
    dropRadius: 2,
    springStrength: 1.2,
    gravity: [0, 0, 0],
    brightnessFlicker: 0.3,
    flickerSpeed: 1.5,
    camera: { position: [0, 0, 4.5] },
    brightness: 1.3,
    glow: 1.2,
    coreIntensity: 1.4,
  },
  vortex: {
    fieldFunction: 'torus',
    fieldParams: { radius: 2, tube: 0.7, coils: 1 },
    particleCount: 6000,
    pointerStrength: 2,
    dropRadius: 1.5,
    camera: { position: [0, 2.5, 4.5], orbitSpeed: 0.18 },
    baseColor: '#7af0ff',
    brightness: 1.1,
    glow: 1,
    coreIntensity: 1,
    brightnessFlicker: 0.4,
    flickerSpeed: 2,
  },
  rain: {
    fieldFunction: 'noise',
    fieldParams: { size: 5 },
    particleCount: 3000,
    gravity: [0, -1.2, 0],
    damping: 0.99,
    springStrength: 0.05,
    particleSize: 100,
    brightnessFlicker: 0.1,
    flickerSpeed: 1,
    baseColor: '#9bb6ff',
    camera: { position: [0, 0, 5] },
    brightness: 0.9,
    glow: 0.5,
    coreIntensity: 1.6,
  },
  attractor: {
    fieldFunction: 'lorenz',
    particleCount: 5000,
    particleSize: 140,
    camera: { position: [0, 1.5, 4], orbitSpeed: 0.08, fov: Math.PI / 3.5 },
    brightnessFlicker: 0.85,
    flickerSpeed: 4,
    baseColor: '#ffd28a',
    brightness: 1.2,
    glow: 1,
    coreIntensity: 1.5,
  },
  swell: {
    fieldFunction: 'wave',
    fieldParams: { size: 5, amplitude: 0.8, frequency: 1.2 },
    particleCount: 6400,
    camera: { position: [0, 2, 5], orbitSpeed: 0.03 },
    pointerStrength: 1.5,
    baseColor: '#a8ffd1',
    brightness: 1,
    glow: 1.4,
    coreIntensity: 0.9,
    brightnessFlicker: 0.3,
    flickerSpeed: 0.8,
  },
} satisfies Record<string, ParticleBackgroundPreset>

export type PresetName = keyof typeof presets
