-- Auto-generated by xomda — Spring Boot Postgres schema for BlogService
-- Apply via Flyway from Spring Boot at startup.

CREATE TABLE author (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  bio TEXT
);

CREATE TABLE post (
  id UUID PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL,
  author_id UUID NOT NULL,
  published_at TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES author(id),
  CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE comment (
  id UUID PRIMARY KEY,
  body TEXT NOT NULL,
  post_id UUID NOT NULL,
  author_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL,
  FOREIGN KEY (post_id) REFERENCES post(id),
  FOREIGN KEY (author_id) REFERENCES author(id)
);
