package com.example;

import com.example.model.Order;
import com.example.model.User;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * Hand-written entry point. Uses the records generated by xomda under
 * {@code src/main/generated/com/example/model/} — proves the generated
 * code compiles together with hand-written wiring.
 */
public final class App {

    private App() {}

    /**
     * Construct a {@link User} and an {@link Order} that references it,
     * then return a short summary. Pure factory — no I/O — so the
     * accompanying JUnit test stays deterministic.
     */
    public static String describeSampleOrder() {
        UUID userId = UUID.fromString("11111111-1111-1111-1111-111111111111");
        User user = new User(userId, "Alice", "alice@example.com");
        UUID orderId = UUID.fromString("22222222-2222-2222-2222-222222222222");
        // `Order.user` is a reference attribute → stored as the UUID.
        Order order = new Order(orderId, userId, new BigDecimal("49.95"));
        return user.name() + " placed order " + order.id() + " for " + order.total();
    }

    public static void main(String[] args) {
        System.out.println(describeSampleOrder());
    }
}
