spring:
  application:
    name: blog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_service
    username: app
    password: app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
