export type { ModelDescriptor } from './file-storage'
export {
  commitVersion,
  createFileStorage,
  createSecondaryModel,
  deleteModel,
  getModelPath,
  getModelsDir,
  getProjectPath,
  getVersion,
  getXomdaDir,
  listModelDescriptors,
  listModels,
  listVersions,
  ModelIdCollisionError,
  ModelNotFoundError,
  PrimaryModelDeletionError,
  readModel,
  readProjectMeta,
  readVersionsIndex,
  renameModel,
  saveProjectMeta,
  writeModel,
} from './file-storage'
